# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4dc831457129bd503474fd3d485c5126118d3f1f1a230ebe9d63927fc338409083125b670d7d7deab929dabb77c84f573d83607629e334d5ac4f1a2e93ba635

test:
  secret_key_base: 78c8b614cb1a62adaa4c8cadf29289bf32feb0bc204333127f135ab00b5cc0403df0f78dc925192d5d9c573c34a52e719cbf4d9adb3fec485a6b169fc6a20851

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
